---
title: Homelab
description: Dashboard NAS Synology
startUrl: https://maxsandman.synology.me:5001

theme: dark
color: slate

showStats: true
hideErrors: true

layout:
  Système:
    style: column
    columns: 1
  Média:
    style: column
    columns: 1
  Téléchargement:
    style: column
    columns: 1
  Perso:
    style: column
    columns: 1
  Outils:
    style: column
    columns: 1
