---
title: Homelab
description: Dashboard NAS Synology
startUrl: https://maxsandman.synology.me:5001

theme: dark
color: slate

showStats: true

layout:
  Système:
    style: row
    columns: 4
  Réseau:
    style: row
    columns: 4
  Monitoring:
    style: row
    columns: 4
  Média:
    style: row
    columns: 4
  Téléchargement:
    style: row
    columns: 4
  Outils:
    style: row
    columns: 4
  Perso:
    style: row
    columns: 4
